using System;
using System.Buffers;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Threading;
using System.Threading.Tasks;
using UnityEngine;
using Wasmtime;

namespace xyz.yewnyx.MediaSandbox
{
    /// <summary>
    /// Wraps the decoder.wasm sandbox. Engine, Linker, and Module are shared across calls;
    /// each async operation creates its own Store + Instance so decodes run fully concurrently.
    /// Unity types (Texture2D, AudioClip) are NOT created here — callers must do that on the main thread.
    /// </summary>
    public sealed class MediaDecoderSandbox : MonoBehaviour
    {
        // Shared (thread-safe)
        private Engine _engine;
        private Linker _linker;
        private Module _module;

        // AttrResult offsets and size are defined in SandboxLayout (generated by build-wasm.ps1).
        private const int AttrResultSize = SandboxLayout.AttrResultSize;

        // Pulley is Wasmtime's portable bytecode interpreter — required on platforms
        // where JIT is prohibited (iOS). Activated by setting target to "pulley64".
        // On iOS this is always enabled regardless of the value below.
        // The native wasmtime library must be built with the `pulley` cargo feature;
        // see .github/workflows/build.yml and scripts/build-wasmtime-*.sh.
        private const bool UsePulley = true;

        private void Awake()
        {
            AssertLayoutSync();
#if UNITY_IOS
            // JIT is prohibited on iOS — Pulley is mandatory.
            _engine = new Engine(MakePulleyConfig());
            if (!_engine.IsPulleyInterpreter)
                throw new InvalidOperationException(
                    "[MediaSandbox] Expected Pulley interpreter but Wasmtime is using Cranelift. " +
                    "Ensure the native wasmtime library was built with --features pulley.");
#else
            if (UsePulley)
            {
                _engine = new Engine(MakePulleyConfig());
                if (!_engine.IsPulleyInterpreter)
                    throw new InvalidOperationException(
                        "[MediaSandbox] Expected Pulley interpreter but Wasmtime is using Cranelift. " +
                        "Ensure the native wasmtime library was built with --features pulley, " +
                        "or set UsePulley = false to use Cranelift explicitly.");
            }
            else
            {
                _engine = new Engine();
            }
#endif
            _linker = new Linker(_engine);
            _linker.DefineWasi();
            _module = Module.FromFile(_engine, WasmPath);
        }

        // ── Pulley config shim ────────────────────────────────────────────────
        // Config.WithTarget() is absent from Wasmtime .NET v44's public API.
        // We call wasmtime_config_target_set from the C API directly, reaching
        // the raw wasm_config_t* via reflection on the SDK's private handle field.

        [DllImport("wasmtime", EntryPoint = "wasmtime_config_target_set",
                   CallingConvention = CallingConvention.Cdecl)]
        private static extern IntPtr NativeConfigTargetSet(
            IntPtr config, [MarshalAs(UnmanagedType.LPUTF8Str)] string? target);

        private static Config MakePulleyConfig()
        {
            var config = new Config();

            // Walk the SDK's private fields to find the raw wasm_config_t* handle.
            IntPtr nativeHandle = IntPtr.Zero;
            const System.Reflection.BindingFlags flags =
                System.Reflection.BindingFlags.NonPublic |
                System.Reflection.BindingFlags.Instance;

            foreach (var field in typeof(Config).GetFields(flags))
            {
                var val = field.GetValue(config);
                if (val is IntPtr p && p != IntPtr.Zero)
                {
                    nativeHandle = p;
                    break;
                }
                if (val is SafeHandle sh && !sh.IsInvalid)
                {
                    nativeHandle = sh.DangerousGetHandle();
                    break;
                }
                if (val != null && val.GetType().IsValueType)
                {
                    foreach (var inner in val.GetType().GetFields(flags))
                    {
                        if (inner.GetValue(val) is IntPtr ip && ip != IntPtr.Zero)
                        {
                            nativeHandle = ip;
                            break;
                        }
                    }
                    if (nativeHandle != IntPtr.Zero) break;
                }
            }

            if (nativeHandle == IntPtr.Zero)
                throw new InvalidOperationException(
                    "[MediaSandbox] Could not locate Wasmtime Config handle via reflection. " +
                    "The SDK's internal layout may have changed.");

            var err = NativeConfigTargetSet(nativeHandle, "pulley64");
            if (err != IntPtr.Zero)
                throw new InvalidOperationException(
                    "[MediaSandbox] wasmtime_config_target_set(\"pulley64\") failed.");

            return config;
        }

        // Fires at play entry in Editor builds; catches C#↔Rust enum drift before
        // any decode call runs. Update both enums and regenerate SandboxLayout.g.cs if this fires.
        [System.Diagnostics.Conditional("UNITY_EDITOR")]
        private static void AssertLayoutSync()
        {
            UnityEngine.Assertions.Assert.AreEqual(
                SandboxLayout.MediaKindValue.Image,     (int)MediaType.Image,
                "[MediaSandbox] MediaType.Image out of sync — run pwsh scripts/build-wasm.ps1");
            UnityEngine.Assertions.Assert.AreEqual(
                SandboxLayout.MediaKindValue.Animation, (int)MediaType.Animation,
                "[MediaSandbox] MediaType.Animation out of sync — run pwsh scripts/build-wasm.ps1");
            UnityEngine.Assertions.Assert.AreEqual(
                SandboxLayout.MediaKindValue.Audio,     (int)MediaType.Audio,
                "[MediaSandbox] MediaType.Audio out of sync — run pwsh scripts/build-wasm.ps1");
            UnityEngine.Assertions.Assert.AreEqual(
                SandboxLayout.EncodeFormat.Png,         (int)ImageFormat.Png,
                "[MediaSandbox] ImageFormat.Png out of sync — run pwsh scripts/build-wasm.ps1");
            UnityEngine.Assertions.Assert.AreEqual(
                SandboxLayout.EncodeFormat.Jpeg,        (int)ImageFormat.Jpeg,
                "[MediaSandbox] ImageFormat.Jpeg out of sync — run pwsh scripts/build-wasm.ps1");
        }

        private void OnDestroy()
        {
            _module?.Dispose();
            _linker?.Dispose();
            _engine?.Dispose();
        }

        private static string WasmPath =>
            System.IO.Path.Combine(Application.streamingAssetsPath, "mediasandbox", "decoder.wasm");

        // ── Per-call instance creation ────────────────────────────────────────

        private (Store store, Instance instance, Memory memory) CreateInstance()
        {
            var store    = new Store(_engine);
            store.SetWasiConfiguration(new WasiConfiguration());
            var instance = _linker.Instantiate(store, _module);
            var memory   = instance.GetMemory("memory")
                           ?? throw new InvalidOperationException("decoder.wasm has no exported 'memory'");
            return (store, instance, memory);
        }

        // ── Low-level helpers ─────────────────────────────────────────────────

        private static int WasmAlloc(Instance instance, int size)
        {
            return instance.GetFunction<int, int>("alloc")!(size);
        }

        private static void WasmDealloc(Instance instance, int ptr, int size)
        {
            instance.GetAction<int, int>("dealloc")!(ptr, size);
        }

        /// <summary>Copies data into WASM memory and returns the allocated pointer.</summary>
        private static int WasmWrite(Instance instance, Memory memory, ReadOnlySpan<byte> data)
        {
            int ptr = WasmAlloc(instance, data.Length);
            data.CopyTo(memory.GetSpan(ptr, data.Length));
            return ptr;
        }

        // ── Public async API ──────────────────────────────────────────────────

        /// <summary>
        /// Reads headers only; cheap. Also the routing point — result.Type tells the caller
        /// which decode method to use next.
        /// </summary>
        public Task<MediaAttributes> QueryAttributesAsync(
            ReadOnlyMemory<byte> data, CancellationToken ct = default)
        {
            return Task.Run(() => {
                var (store, instance, memory) = CreateInstance();
                using (store)
                {
                    return QueryAttributesCore(instance, memory, data.Span);
                }
            }, ct);
        }

        private static MediaAttributes QueryAttributesCore(
            Instance instance, Memory memory, ReadOnlySpan<byte> data)
        {
            int dataPtr = WasmWrite(instance, memory, data);
            int attrPtr = WasmAlloc(instance, AttrResultSize);
            try
            {
                instance.GetFunction<int, int, int, int>("query_attributes")!(dataPtr, data.Length, attrPtr);
                return ReadAttrResult(memory, attrPtr);
            }
            finally
            {
                WasmDealloc(instance, dataPtr, data.Length);
                WasmDealloc(instance, attrPtr, AttrResultSize);
            }
        }

        private static MediaAttributes ReadAttrResult(Memory memory, int ptr)
        {
            long durationMs         = memory.ReadInt64(ptr + SandboxLayout.AttrResultField.DurationMs);
            long requiredBufferSize = memory.ReadInt64(ptr + SandboxLayout.AttrResultField.RequiredBufferSize);
            int  mediaType          = memory.ReadInt32(ptr + SandboxLayout.AttrResultField.MediaType);
            int  width              = memory.ReadInt32(ptr + SandboxLayout.AttrResultField.Width);
            int  height             = memory.ReadInt32(ptr + SandboxLayout.AttrResultField.Height);
            int  frameCount         = memory.ReadInt32(ptr + SandboxLayout.AttrResultField.FrameCount);
            int  sampleRate         = memory.ReadInt32(ptr + SandboxLayout.AttrResultField.SampleRate);
            int  channelCount       = memory.ReadInt32(ptr + SandboxLayout.AttrResultField.ChannelCount);
            int  errorCode          = memory.ReadInt32(ptr + SandboxLayout.AttrResultField.ErrorCode);
            uint flags              = (uint)memory.ReadInt32(ptr + SandboxLayout.AttrResultField.Flags);

            if (errorCode != 0)
                throw new Exception($"query_attributes error code: {errorCode}");

            bool canHaveAlpha = (flags & SandboxLayout.AttrFlags.AlphaPossible) != 0;
            return new MediaAttributes(
                (MediaType)mediaType, width, height, frameCount,
                sampleRate, channelCount, durationMs, requiredBufferSize, canHaveAlpha);
        }

        /// <summary>
        /// Decodes a static image (PNG, JPEG, BMP, TIFF, WebP, HDR, QOI) to raw RGBA bytes.
        /// Caller creates Texture2D on the main thread from the returned RawImageData.
        /// </summary>
        public Task<RawImageData> DecodeImageAsync(
            ReadOnlyMemory<byte> data, CancellationToken ct = default)
        {
            return Task.Run(async () => {
                var attrs = await QueryAttributesAsync(data, ct);

                if (attrs.Type != MediaType.Image)
                    throw new InvalidOperationException($"Expected Image, got {attrs.Type}");

                CheckPathological(attrs, data.Length);

                var (tw, th) = CapDimensions(attrs.Width, attrs.Height);
                var (store, instance, memory) = CreateInstance();
                using (store)
                {
                    return DecodeImageCore(instance, memory, data.Span, tw, th);
                }
            }, ct);
        }

        private static RawImageData DecodeImageCore(
            Instance instance, Memory memory, ReadOnlySpan<byte> data, int targetW, int targetH)
        {
            int outLen  = targetW * targetH * 4;
            int dataPtr = WasmWrite(instance, memory, data);
            int outPtr  = WasmAlloc(instance, outLen);
            byte[] pooled = null;
            try
            {
                int code = instance.GetFunction<int, int, int, int, int, int, int>("decode_image")!
                    (dataPtr, data.Length, outPtr, outLen, targetW, targetH);
                if (code != 0) throw new Exception($"decode_image failed ({code})");

                pooled = ArrayPool<byte>.Shared.Rent(outLen);
                memory.GetSpan(outPtr, outLen).CopyTo(pooled);
                return new RawImageData(targetW, targetH, pooled, outLen);
            }
            catch
            {
                if (pooled != null) ArrayPool<byte>.Shared.Return(pooled);
                throw;
            }
            finally
            {
                WasmDealloc(instance, dataPtr, data.Length);
                WasmDealloc(instance, outPtr, outLen);
            }
        }

        /// <summary>
        /// Decodes an animation (GIF or WebP, static or animated) frame by frame.
        /// Progress is reported in [0,1] as each frame completes; callbacks fire on the
        /// thread pool so they reach the Unity main thread via SynchronizationContext
        /// spread across the real decode time rather than in a post-decode burst.
        /// A single-frame result means the source was a still image — spawner handles both.
        /// </summary>
        public Task<AnimatedImageData> DecodeAnimationAsync(
            ReadOnlyMemory<byte> data,
            IProgress<float> progress = null,
            CancellationToken ct = default)
        {
            return Task.Run(async () => {
                var attrs = await QueryAttributesAsync(data, ct);

                if (attrs.Type != MediaType.Animation)
                    throw new InvalidOperationException($"Expected Animation, got {attrs.Type}");

                CheckPathological(attrs, data.Length);

                var (tw, th) = CapDimensions(attrs.Width, attrs.Height);
                var (store, instance, memory) = CreateInstance();
                using (store)
                {
                    return DecodeAnimationStreaming(instance, memory, data.Span, attrs.FrameCount, tw, th, progress);
                }
            }, ct);
        }

        private static AnimatedImageData DecodeAnimationStreaming(
            Instance instance, Memory memory, ReadOnlySpan<byte> data,
            int frameCount, int targetW, int targetH, IProgress<float> progress)
        {
            int frameBytes = targetW * targetH * 4;
            // animation_open consumes dataPtr internally — host must not dealloc it.
            int dataPtr  = WasmWrite(instance, memory, data);
            int delayPtr = WasmAlloc(instance, 4);
            int rgbaPtr  = WasmAlloc(instance, frameBytes);
            int handle   = 0;
            var frames   = new List<AnimationFrame>(frameCount);
            try
            {
                handle = instance.GetFunction<int, int, int, int, int>("animation_open")!
                    (dataPtr, data.Length, targetW, targetH);
                if (handle == 0) throw new Exception("animation_open failed");

                int status;
                while ((status = instance.GetFunction<int, int, int, int, int>("animation_next_frame")!
                    (handle, delayPtr, rgbaPtr, frameBytes)) == 0)
                {
                    int delayMs  = memory.ReadInt32(delayPtr);
                    byte[] pooled = ArrayPool<byte>.Shared.Rent(frameBytes);
                    memory.GetSpan(rgbaPtr, frameBytes).CopyTo(pooled);
                    frames.Add(new AnimationFrame(pooled, frameBytes, delayMs));
                    progress?.Report(frames.Count / (float)frameCount);
                }
                if (status != 1) throw new Exception($"animation_next_frame error ({status})");

                return new AnimatedImageData(targetW, targetH, frames.ToArray());
            }
            catch
            {
                foreach (var f in frames) f.Dispose();
                throw;
            }
            finally
            {
                if (handle != 0)
                    instance.GetAction<int>("animation_close")!(handle);
                WasmDealloc(instance, delayPtr, 4);
                WasmDealloc(instance, rgbaPtr, frameBytes);
            }
        }

        /// <summary>
        /// Decodes audio to interleaved f32 PCM samples.
        /// Caller creates AudioClip on the main thread from the returned RawAudioData.
        /// </summary>
        public Task<RawAudioData> DecodeAudioAsync(
            ReadOnlyMemory<byte> data,
            CancellationToken ct = default)
        {
            return Task.Run(async () => {
                if (data.Length > SandboxLimits.MaxFileSizeBytes)
                    throw new PathologicalMediaException(
                        $"Audio file too large: {data.Length:N0} bytes (limit {SandboxLimits.MaxFileSizeBytes:N0})");

                var attrs = await QueryAttributesAsync(data, ct);
                if (attrs.Type != MediaType.Audio)
                    throw new InvalidOperationException($"Expected Audio, got {attrs.Type}");

                var (store, instance, memory) = CreateInstance();
                using (store) { return DecodeAudioCore(instance, memory, data.Span); }
            }, ct);
        }

        private static RawAudioData DecodeAudioCore(
            Instance instance, Memory memory, ReadOnlySpan<byte> data)
        {
            int outPtrAddr = WasmAlloc(instance, 4);
            int outLenAddr = WasmAlloc(instance, 4);
            int srAddr     = WasmAlloc(instance, 4);
            int chAddr     = WasmAlloc(instance, 4);
            int dataPtr    = WasmWrite(instance, memory, data);
            try
            {
                int code = instance.GetFunction<int, int, int, int, int, int, int>("decode_audio")!
                    (dataPtr, data.Length, outPtrAddr, outLenAddr, srAddr, chAddr);
                if (code != 0) throw new Exception($"decode_audio failed ({code})");

                int sampleDataPtr = memory.ReadInt32(outPtrAddr);
                int sampleDataLen = memory.ReadInt32(outLenAddr);
                int sampleRate    = memory.ReadInt32(srAddr);
                int channels      = memory.ReadInt32(chAddr);

                int sampleCount = sampleDataLen / 4;
                var samples     = new float[sampleCount];
                MemoryMarshal
                    .Cast<byte, float>(memory.GetSpan(sampleDataPtr, sampleDataLen))
                    .CopyTo(samples);

                WasmDealloc(instance, sampleDataPtr, sampleDataLen);

                return new RawAudioData(samples, sampleRate, channels);
            }
            finally
            {
                WasmDealloc(instance, dataPtr, data.Length);
                WasmDealloc(instance, outPtrAddr, 4);
                WasmDealloc(instance, outLenAddr, 4);
                WasmDealloc(instance, srAddr, 4);
                WasmDealloc(instance, chAddr, 4);
            }
        }

        /// <summary>
        /// Queries EXIF fields and XMP packet from an image file.
        /// Returns a JSON string with "exif" (object) and/or "xmp_packet" (raw XML string) keys,
        /// or "{}" if no metadata is present. The caller parses the JSON with
        /// System.Text.Json or System.Xml.Linq as needed.
        /// </summary>
        public Task<string> QueryMetadataAsync(
            ReadOnlyMemory<byte> data, CancellationToken ct = default)
        {
            return Task.Run(() => {
                var (store, instance, memory) = CreateInstance();
                using (store)
                {
                    return QueryMetadataCore(instance, memory, data.Span);
                }
            }, ct);
        }

        private static string QueryMetadataCore(
            Instance instance, Memory memory, ReadOnlySpan<byte> data)
        {
            int outPtrAddr = WasmAlloc(instance, 4);
            int outLenAddr = WasmAlloc(instance, 4);
            int dataPtr    = WasmWrite(instance, memory, data);
            try
            {
                int code = instance.GetFunction<int, int, int, int, int>("query_metadata")!
                    (dataPtr, data.Length, outPtrAddr, outLenAddr);
                if (code != 0) return "{}";

                int outPtr = memory.ReadInt32(outPtrAddr);
                int outLen = memory.ReadInt32(outLenAddr);
                try
                {
                    return System.Text.Encoding.UTF8.GetString(memory.GetSpan(outPtr, outLen));
                }
                finally
                {
                    WasmDealloc(instance, outPtr, outLen);
                }
            }
            finally
            {
                WasmDealloc(instance, dataPtr, data.Length);
                WasmDealloc(instance, outPtrAddr, 4);
                WasmDealloc(instance, outLenAddr, 4);
            }
        }

        /// <summary>
        /// Strips EXIF, XMP, and associated metadata from a JPEG, PNG, or WebP file
        /// without re-encoding pixel data. Returns the stripped bytes.
        /// For unsupported formats (TIFF, GIF, BMP, …) returns the original bytes unchanged;
        /// use EncodeImageAsync for a clean round-trip on those formats.
        /// </summary>
        public Task<byte[]> StripMetadataAsync(
            ReadOnlyMemory<byte> data, CancellationToken ct = default)
        {
            return Task.Run(() => {
                var (store, instance, memory) = CreateInstance();
                using (store)
                {
                    return StripMetadataCore(instance, memory, data.Span);
                }
            }, ct);
        }

        private static byte[] StripMetadataCore(
            Instance instance, Memory memory, ReadOnlySpan<byte> data)
        {
            int outPtrAddr = WasmAlloc(instance, 4);
            int outLenAddr = WasmAlloc(instance, 4);
            int dataPtr    = WasmWrite(instance, memory, data);
            try
            {
                int code = instance.GetFunction<int, int, int, int, int>("strip_metadata")!
                    (dataPtr, data.Length, outPtrAddr, outLenAddr);

                if (code == 1)
                    return data.ToArray(); // format not supported — original unchanged

                if (code != 0)
                    throw new Exception($"strip_metadata failed ({code})");

                int outPtr = memory.ReadInt32(outPtrAddr);
                int outLen = memory.ReadInt32(outLenAddr);
                try
                {
                    return memory.GetSpan(outPtr, outLen).ToArray();
                }
                finally
                {
                    WasmDealloc(instance, outPtr, outLen);
                }
            }
            finally
            {
                WasmDealloc(instance, dataPtr, data.Length);
                WasmDealloc(instance, outPtrAddr, 4);
                WasmDealloc(instance, outLenAddr, 4);
            }
        }

        /// <summary>
        /// Encodes raw RGBA to the requested image format.
        /// Returns compressed bytes; does not interact with Unity types.
        /// </summary>
        public Task<byte[]> EncodeImageAsync(
            RawImageData image, ImageFormat format, CancellationToken ct = default)
        {
            return Task.Run(() => {
                var (store, instance, memory) = CreateInstance();
                using (store)
                {
                    return EncodeImageCore(instance, memory, image, format);
                }
            }, ct);
        }

        private static byte[] EncodeImageCore(
            Instance instance, Memory memory, RawImageData image, ImageFormat format)
        {
            int outPtrAddr = WasmAlloc(instance, 4);
            int outLenAddr = WasmAlloc(instance, 4);
            int rgbaPtr    = WasmWrite(instance, memory, image.Rgba.Span);
            try
            {
                int code = instance.GetFunction<int, int, int, int, int, int, int>("encode_image")!
                    (rgbaPtr, image.Width, image.Height, (int)format, outPtrAddr, outLenAddr);
                if (code != 0) throw new Exception($"encode_image failed ({code})");

                int outPtr = memory.ReadInt32(outPtrAddr);
                int outLen = memory.ReadInt32(outLenAddr);
                var result = memory.GetSpan(outPtr, outLen).ToArray();

                WasmDealloc(instance, outPtr, outLen);
                return result;
            }
            finally
            {
                WasmDealloc(instance, rgbaPtr, image.Rgba.Length); // ReadOnlyMemory.Length is the exact slice length
                WasmDealloc(instance, outPtrAddr, 4);
                WasmDealloc(instance, outLenAddr, 4);
            }
        }

        // ── Pathological guard ────────────────────────────────────────────────

        private static (int w, int h) CapDimensions(int w, int h)
        {
            int max = SandboxLimits.MaxDecodeDimension;
            if (w <= max && h <= max) return (w, h);
            float scale = Math.Min((float)max / w, (float)max / h);
            return (Math.Max(1, (int)(w * scale)), Math.Max(1, (int)(h * scale)));
        }

        private static void CheckPathological(MediaAttributes attrs, long fileSize)
        {
            if (fileSize > SandboxLimits.MaxFileSizeBytes)
                throw new PathologicalMediaException(
                    $"File too large: {fileSize:N0} bytes (limit {SandboxLimits.MaxFileSizeBytes:N0})");
        }
    }
}
